# docker-compose.yml
version: '3'
services:
  db:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - ${TEST_DB_PORT}:5432
  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
